name: CI

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]
  workflow_dispatch:

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache-dependency-path: applications/server/package-lock.json
          cache: npm
      
      - name: Install dependencies
        run: npm ci
        working-directory: applications/server

      - name: Run linting
        run: npm run lint
        working-directory: applications/server

      - name: Run test cases
        run: npm run test
        working-directory: applications/server

      - name: Build application
        run: npm run build
        working-directory: applications/server
